(function (global) {
  'use strict';
  const ENABLE='tp_perf_trace_enabled_v1', HISTORY='tp_perf_trace_pages_v1', NAV='tp_perf_trace_pending_nav_v1';
  const MAX_EVENTS=1200, MAX_PAGES=6, tracked=new Set(['taskpoints_v1','taskpoints_pending_habit_deltas_v1','taskpoints_storage_data_loss_guard_v1','taskpoints_state_revision_v1','taskpoints_safety_vault_meta_v1','tp_projects_v1']);
  const perf=global.performance, now=()=>perf?.now?.()??Date.now(), epoch=()=>Date.now();
  const sget=k=>{try{return global.sessionStorage?.getItem?.(k)??null}catch(_){return null}}, sset=(k,v)=>{try{global.sessionStorage?.setItem?.(k,v);return true}catch(_){return false}}, sdel=k=>{try{global.sessionStorage?.removeItem?.(k)}catch(_){}};
  let q=null; try{q=new URLSearchParams(global.location?.search||'')}catch(_){} const requested=q?.get?.('perf')??q?.get?.('tpperf');
  if(requested==='0'||requested==='off')sdel(ENABLE); if(requested==='1'||requested==='on')sset(ENABLE,'1');
  const active=sget(ENABLE)==='1';
  if(!active){
    const mountActivator=()=>{if(!/\/settings(?:\.html)?$/.test(String(global.location?.pathname||''))||!global.document?.body||global.document.getElementById('tpPerfTraceEnableButton'))return;const b=global.document.createElement('button');b.id='tpPerfTraceEnableButton';b.type='button';b.textContent='Enable Perf Trace';b.style.cssText='position:fixed;right:10px;bottom:96px;z-index:2147483645;border:1px solid #64748b;border-radius:999px;background:#111827;color:#f8fafc;padding:7px 10px;font:600 11px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;opacity:.9';b.addEventListener('click',()=>{sset(ENABLE,'1');global.location.reload()});global.document.body.appendChild(b)};
    if(global.document?.readyState==='loading')global.document.addEventListener('DOMContentLoaded',mountActivator,{once:true});else mountActivator();
    return;
  }
  if(global.TaskPointsPerf?.enabled)return;
  let internal=0,panel=null,hooks=false; const inside=fn=>{internal++;try{return fn()}finally{internal=Math.max(0,internal-1)}};
  const page={schemaVersion:1,id:`${epoch().toString(36)}-${Math.random().toString(36).slice(2,8)}`,path:String(global.location?.pathname||''),title:String(global.document?.title||''),startedAtISO:new Date().toISOString(),timeOrigin:Number(perf?.timeOrigin)||null,userAgent:String(global.navigator?.userAgent||''),hardwareConcurrency:Number(global.navigator?.hardwareConcurrency)||null,deviceMemory:Number(global.navigator?.deviceMemory)||null,events:[]};
  const bundleStart=now();
  const clean=d=>{if(!d||typeof d!=='object')return d==null?null:String(d);const o={};for(const[k,v]of Object.entries(d)){if(v==null||['boolean','number'].includes(typeof v))o[k]=v;else if(typeof v==='string')o[k]=v.length>220?`${v.slice(0,217)}...`:v;else o[k]=Array.isArray(v)?`[array:${v.length}]`:'[object]'}return o};
  function rec(type,name,ms,detail){if(internal)return null;const e={atMs:+now().toFixed(2),epochMs:epoch(),type,name,...(Number.isFinite(+ms)?{durationMs:+(+ms).toFixed(2)}:{}),...(detail==null?{}:{detail:clean(detail)})};page.events.push(e);if(page.events.length>MAX_EVENTS)page.events.splice(0,page.events.length-MAX_EVENTS);badge();return e}
  const mark=(n,d)=>rec('mark',n,null,d), duration=(n,ms,d)=>rec('duration',n,ms,d), span=(n,d)=>{const st=now();let done=false;return x=>{if(done)return;done=true;return duration(n,now()-st,{...(d||{}),...(x||{})})}};
  const summary=v=>typeof v==='string'?{kind:'string',length:v.length}:(!v||typeof v!=='object'?{kind:typeof v}:{kind:Array.isArray(v)?'array':'object',length:Array.isArray(v)?v.length:undefined,completions:Array.isArray(v.completions)?v.completions.length:undefined,matchups:Array.isArray(v.matchups)?v.matchups.length:undefined,gameHistory:Array.isArray(v.gameHistory)?v.gameHistory.length:undefined,tasks:Array.isArray(v.tasks)?v.tasks.length:undefined});
  const history=()=>inside(()=>{try{const x=JSON.parse(sget(HISTORY)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}});
  function persist(){return inside(()=>{const h=history().filter(x=>x?.id!==page.id);h.push({...page,endedAtISO:new Date().toISOString()});return sset(HISTORY,JSON.stringify(h.slice(-MAX_PAGES)))})}
  function report(){return inside(()=>{const pages=history().filter(x=>x?.id!==page.id);pages.push({...page,capturedAtISO:new Date().toISOString()});const all=pages.flatMap(p=>(p.events||[]).map(e=>({page:p.path,...e}))),timed=all.filter(e=>Number.isFinite(+e.durationMs)),c=global.TaskPointsCore;return{schemaVersion:1,generatedAtISO:new Date().toISOString(),currentPath:page.path,pageCount:pages.length,eventCount:all.length,stallCount:all.filter(e=>e.name==='eventLoop.stall'||e.type==='longtask').length,hotCacheStatus:c?.getStateHotCacheStatus?.()||null,storageMaintenanceIdleStatus:c?.getStorageMaintenanceIdleStatus?.()||null,topDurations:timed.sort((a,b)=>b.durationMs-a.durationMs).slice(0,60),pages}})}
  const text=()=>inside(()=>JSON.stringify(report(),null,2));
  async function copy(){const t=text();try{if(typeof global.navigator?.clipboard?.writeText!=='function')throw 0;await global.navigator.clipboard.writeText(t);return true}catch(_){try{const a=global.document.createElement('textarea');a.value=t;a.style.cssText='position:fixed;opacity:0';global.document.body.appendChild(a);a.select();const ok=global.document.execCommand?.('copy')!==false;a.remove();return ok}catch(_){return false}}}
  function download(){const b=new Blob([text()],{type:'application/json'}),u=URL.createObjectURL(b),a=global.document.createElement('a');a.href=u;a.download=`taskpoints-perf-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;global.document.body.appendChild(a);a.click();a.remove();global.setTimeout(()=>URL.revokeObjectURL(u),1000);return true}
  function clear(){page.events.length=0;sdel(HISTORY);sdel(NAV);mark('trace.cleared')}
  function disable(){persist();sdel(ENABLE);return true}
  const etime=e=>{const x=+e?.timeStamp;if(!Number.isFinite(x))return null;if(x>1e12&&Number.isFinite(+perf?.timeOrigin))return x-perf.timeOrigin;if(x>=0&&x<1e9)return x;return null};
  const desc=t=>!t?'':`${String(t.tagName||'').toLowerCase()}${t.id?`#${t.id}`:''}`.slice(0,100);
  const relevant=t=>{try{return!!t?.closest?.('#homePanelScwm,#score-dashboard-v1,#score-dashboard-v2,.scwm-card,.scoreV2-cell,.habitDay,[id$="EditModal"],[data-export-button],[data-export-images],[data-home-tab],a,button,input,textarea,select')}catch(_){return false}};
  function interactions(){const d=global.document;if(!d?.addEventListener)return;for(const n of['pointerdown','click'])d.addEventListener(n,e=>{if(!relevant(e.target))return;const t=e.target?.closest?.('[data-export-button],[data-export-images],.scoreV2-cell,.habitDay,[data-home-tab],a,button,input,textarea,select')||e.target;mark(`interaction.${n}`,{target:desc(t)})},true);for(const n of['beforeinput','input','keydown'])d.addEventListener(n,e=>{if(!relevant(e.target))return;const ts=etime(e),delay=ts==null?null:Math.max(0,now()-ts);mark(`interaction.${n}`,{target:desc(e.target),processingDelayMs:delay==null?null:+delay.toFixed(2),inputType:String(e.inputType||''),key:n==='keydown'?String(e.key||''):''});const st=now();global.requestAnimationFrame?.(()=>duration(`interaction.${n}.toPaint`,now()-st,{target:desc(e.target)}))},true);d.addEventListener('click',e=>{const a=e.target?.closest?.('a[href]');if(!a)return;let u;try{u=new URL(a.href,global.location?.href)}catch(_){return}if(u.origin!==global.location?.origin)return;const p={atEpochMs:epoch(),from:String(global.location?.pathname||''),to:u.pathname,label:String(a.textContent||'').trim().slice(0,70)};inside(()=>sset(NAV,JSON.stringify(p)));mark('navigation.click',p)},true)}
  function pendingNav(){const p=inside(()=>{let x=null;try{x=JSON.parse(sget(NAV)||'null')}catch(_){}sdel(NAV);return x});if(!p?.atEpochMs)return;const ms=epoch()-+p.atEpochMs;if(ms>=0&&ms<60000)duration('navigation.clickToCoreBootstrap',ms,{from:p.from||'',to:page.path,label:p.label||''})}
  function navTiming(){try{const n=perf?.getEntriesByType?.('navigation')?.[0];if(n)mark('navigation.timing',{type:n.type||'',responseStartMs:+n.responseStart||0,responseEndMs:+n.responseEnd||0,domInteractiveMs:+n.domInteractive||0,domContentLoadedMs:+n.domContentLoadedEventEnd||0,loadEventEndMs:+n.loadEventEnd||0,transferSize:+n.transferSize||0,encodedBodySize:+n.encodedBodySize||0,decodedBodySize:+n.decodedBodySize||0})}catch(_){}}
  function observers(){if(typeof global.PerformanceObserver!=='function')return;try{const o=new global.PerformanceObserver(l=>l.getEntries().forEach(e=>rec('longtask','browser.longtask',e.duration,{startTime:e.startTime,name:e.name||''})));o.observe({type:'longtask',buffered:true})}catch(_){}try{const o=new global.PerformanceObserver(l=>l.getEntries().forEach(e=>{const delay=+e.processingStart-+e.startTime;if(e.duration>=40||delay>=40)rec('eventTiming',`browser.event.${e.name||'event'}`,e.duration,{processingDelayMs:Number.isFinite(delay)?+delay.toFixed(2):null,interactionId:+e.interactionId||0})}));o.observe({type:'event',buffered:true,durationThreshold:16})}catch(_){}}
  function watchdog(){let expected=now()+100;const tick=()=>{const cur=now(),late=cur-expected;if(late>=60)duration('eventLoop.stall',late,{expectedIntervalMs:100});expected=cur+100;global.setTimeout?.(tick,100)};global.setTimeout?.(tick,100)}
  function storageTrace(){const p=global.Storage?.prototype;if(!p||p.__tpPerfStorageTracing)return;try{Object.defineProperty(p,'__tpPerfStorageTracing',{value:true,configurable:true})}catch(_){return}for(const n of['getItem','setItem','removeItem']){const orig=p[n];if(typeof orig!=='function')continue;p[n]=function(k,v){const st=now();try{return orig.apply(this,arguments)}finally{const ms=now()-st,key=String(k||''),importantWrite=n!=='getItem'&&tracked.has(key);if(!key.startsWith('tp_perf_trace_')&&(ms>=8||importantWrite))duration(`storage.${n}`,ms,{key,valueLength:n==='setItem'&&typeof v==='string'?v.length:null})}}}}
  function jsonTrace(){if(!global.JSON||global.JSON.stringify?.__tpPerfWrapped)return;const orig=global.JSON.stringify;const w=function(v){if(internal)return orig.apply(this,arguments);const st=now();let out;try{out=orig.apply(this,arguments)}finally{const ms=now()-st;if(ms>=8)duration('json.stringify',ms,{...summary(v),outputLength:typeof out==='string'?out.length:null})}return out};Object.defineProperty(w,'__tpPerfWrapped',{value:true});global.JSON.stringify=w}
  function cloneTrace(){if(typeof global.structuredClone!=='function'||global.structuredClone.__tpPerfWrapped)return;const orig=global.structuredClone.bind(global);const w=function(v){const st=now();try{return orig.apply(global,arguments)}finally{const ms=now()-st;if(ms>=8)duration('structuredClone',ms,summary(v))}};Object.defineProperty(w,'__tpPerfWrapped',{value:true});global.structuredClone=w}
  function idbTrace(){const p=global.IDBDatabase?.prototype;if(!p||p.transaction?.__tpPerfWrapped)return;const orig=p.transaction,w=function(stores,mode){const st=now(),db=String(this?.name||''),tx=orig.apply(this,arguments),names=Array.isArray(stores)?stores.join(','):String(stores||''),done=o=>duration('indexedDB.transaction',now()-st,{db,stores:names,mode:String(mode||'readonly'),outcome:o});try{tx.addEventListener?.('complete',()=>done('complete'),{once:true});tx.addEventListener?.('abort',()=>done('abort'),{once:true});tx.addEventListener?.('error',()=>done('error'),{once:true})}catch(_){}return tx};Object.defineProperty(w,'__tpPerfWrapped',{value:true});p.transaction=w}
  function wrap(owner,name,label,detailFn){const orig=owner?.[name];if(typeof orig!=='function'||orig.__tpPerfWrapped)return false;const w=function(){let d=null;try{d=detailFn?.(arguments)||null}catch(_){}const end=span(label,d);let r;try{r=orig.apply(this,arguments)}catch(e){end({outcome:'throw',error:String(e?.message||e).slice(0,150)});throw e}if(r&&typeof r.then==='function'){try{r.then(()=>end({outcome:'resolved'}),e=>end({outcome:'rejected',error:String(e?.message||e).slice(0,150)}))}catch(_){end({outcome:'promise'})}}else end({outcome:'return'});return r};Object.defineProperty(w,'__tpPerfWrapped',{value:true});owner[name]=w;return true}
  function coreHooks(){const c=global.TaskPointsCore;if(!c)return false;wrap(c,'parseTaskPointsStorageJson','core.parseTaskPointsStorageJson',a=>({rawLength:typeof a[0]==='string'?a[0].length:null}));wrap(c,'readTaskPointsStoredState','core.readTaskPointsStoredState',a=>({storageKey:String(a[0]||'')}));wrap(c,'writeTaskPointsStoredState','core.writeTaskPointsStoredState',a=>summary(a[0]));wrap(c,'saveStateSnapshot','core.saveStateSnapshot',a=>({...summary(a[0]),savePath:String(a[1]?.savePath||a[1]?.source||a[1]?.reason||'')}));wrap(c,'saveValidatedSnapshot','core.saveValidatedSnapshot',a=>({...summary(a[0]),source:String(a[1]?.source||'')}));wrap(c,'shadowSourceSummary','core.shadowSourceSummary',a=>summary(a[0]));wrap(c,'shadowCanonicalJson','core.shadowCanonicalJson',a=>summary(a[0]));wrap(c,'loadAppState','core.loadAppState');return true}
  function pageHooks(){for(const[n,l]of[['save','page.save'],['renderAll','page.renderAll'],['renderStats','page.renderStats'],['getDerived','page.getDerived'],['captureLiveDiffPoint','page.captureLiveDiffPoint'],['exportDataFallback','page.exportDataFallback'],['exportBackupWithImagesFallback','page.exportBackupWithImagesFallback'],['exportOGDataOnly','page.exportOGDataOnly']])wrap(global,n,l)}
  function installHooks(){if(!hooks){coreHooks();hooks=true}else coreHooks();pageHooks()}
  function bundleReady(){duration('core.bundle.evaluate',now()-bundleStart,{path:page.path});installHooks();for(const ms of[0,100,500,1500,3000])global.setTimeout?.(installHooks,ms)}
  function badge(){const b=global.document?.getElementById?.('tpPerfTraceButton');if(b)b.textContent=`PERF ${page.events.length}`}
  function close(){panel?.remove?.();panel=null}
  function open(){if(!global.document?.body)return;close();panel=global.document.createElement('div');panel.id='tpPerfTracePanel';panel.style.cssText='position:fixed;top:calc(env(safe-area-inset-top, 0px) + 18px);right:12px;bottom:calc(env(safe-area-inset-bottom, 0px) + 18px);left:12px;z-index:2147483647;background:#0b0f14;color:#f8fafc;border:1px solid #475569;border-radius:14px;padding:14px;overflow:auto;font:14px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-shadow:0 12px 40px rgba(0,0,0,.5)';const r=report(),top=r.topDurations.slice(0,12).map(x=>`${(+x.durationMs).toFixed(0)} ms — ${x.name} (${x.page})`).join('\n')||'No timed events yet.',esc=top.replace(/[&<>]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[ch]));panel.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;position:sticky;top:0;z-index:2;background:#0b0f14;padding-bottom:8px"><strong>TaskPoints performance trace</strong><button data-p-close style="min-width:72px;min-height:44px;padding:8px 14px;border:1px solid #64748b;border-radius:10px;background:#111827;color:#f8fafc;font-size:16px">Close</button></div><div style="margin:10px 0;color:#cbd5e1">Events: ${r.eventCount} · stalls: ${r.stallCount} · pages: ${r.pageCount}</div><pre style="white-space:pre-wrap;background:#111827;padding:10px;border-radius:8px;max-height:45vh;overflow:auto">${esc}</pre><div style="display:flex;flex-wrap:wrap;gap:8px"><button data-p-copy>Copy report</button><button data-p-down>Download JSON</button><button data-p-clear>Clear trace</button><button data-p-disable>Disable after reload</button></div><div data-p-status style="margin-top:8px;color:#94a3b8"></div>`;panel.querySelector('[data-p-close]')?.addEventListener('click',close);panel.querySelector('[data-p-copy]')?.addEventListener('click',async()=>{const ok=await copy(),s=panel?.querySelector?.('[data-p-status]');if(s)s.textContent=ok?'Report copied.':'Copy failed; use Download JSON.'});panel.querySelector('[data-p-down]')?.addEventListener('click',download);panel.querySelector('[data-p-clear]')?.addEventListener('click',()=>{clear();close();open()});panel.querySelector('[data-p-disable]')?.addEventListener('click',()=>{disable();const s=panel?.querySelector?.('[data-p-status]');if(s)s.textContent='Tracing will be off after the next reload.'});global.document.body.appendChild(panel)}
  function installBadge(){if(!global.document?.body||global.document.getElementById('tpPerfTraceButton'))return;const b=global.document.createElement('button');b.id='tpPerfTraceButton';b.type='button';b.textContent=`PERF ${page.events.length}`;const mobile=global.matchMedia?.('(max-width: 768px)')?.matches===true;b.style.cssText=mobile?'position:fixed;right:10px;bottom:calc(env(safe-area-inset-bottom, 0px) + 185px);top:auto;z-index:2147483646;border:1px solid #64748b;border-radius:999px;background:#111827;color:#f8fafc;padding:7px 11px;font:600 12px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;opacity:.92;min-height:36px':'position:fixed;top:8px;right:8px;z-index:2147483646;border:1px solid #64748b;border-radius:999px;background:#111827;color:#f8fafc;padding:5px 9px;font:600 11px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;opacity:.88';b.addEventListener('click',open);global.document.body.appendChild(b)}
  global.TaskPointsPerf={enabled:true,version:2,page,mark,duration,span,buildReport:report,reportText:text,copyReport:copy,downloadReport:download,clearTrace:clear,disableTrace:disable,persistCurrentPage:persist,installHooks,recordBundleReady:bundleReady};
  mark('trace.enabled',{path:page.path});pendingNav();storageTrace();jsonTrace();cloneTrace();idbTrace();interactions();observers();watchdog();navTiming();
  if(global.document?.readyState==='loading')global.document.addEventListener('DOMContentLoaded',()=>{installBadge();installHooks()},{once:true});else{installBadge();installHooks()}
  global.addEventListener?.('load',()=>global.setTimeout?.(navTiming,0),{once:true});global.addEventListener?.('pagehide',persist,{capture:true});
})(typeof window!=='undefined'?window:globalThis);
